nome = input("Qual é o seu nome? ")
print()
idade = input("Qual é a sua idade? ")
print()
print("Olá,", nome)
print()
aniversario = input(f"Ei {nome}, você disse que tem {idade} anos. Que dia você faz aniversário? ")
print()
print(f"Que legal, {nome}! Então você faz aniversário no dia {aniversario}!")
